Styling for mobile version
williamrolando88/es-tournament pull request #2
Opened 2021-11-17 21:23 UTC by williamrolando88

In this branch the following changes were made:
- Added styling for mobile version
- Added styling for the desktop version
- Added hideable navbar menu
- Added dynamic feature elements generation
- Added an appropriate README file

2021-11-18 00:15 UTC, BrianSammit requested changes
# CHANGES REQUIRED 🔴 🛑
Hello @williamrolando88, great job you are doing so far in this project. 💯
TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 
- I really like that you implement links to move inside the page 🥇 
- Really nice job implementing the game features game with javascript You use JSON to achieve that, good job for the extra effort.

However, there are a few changes to make to move to the next project 🛠️ . Keep working hard 💪 💻 

## Required Changes ♻️

- [ ] kindly add `.hintrc`, `.stylelintrc.json`, and `.eslintrc.json` to `.gitignore` because those files are to check the linters locally and you don't need them to run the project. 

See my inline comment to know what changes are needed. 👇 👀 

Please make these required changes and send it again for another review 👍 💪
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
# HAPPY CODING!!! 😄 

![tenor-1](https://user-images.githubusercontent.com/64173189/142303429-6a1e0d19-eb88-42d6-aeb9-1b3f233115e4.gif)


**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

--------

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-18 00:15 UTC, BrianSammit commented on index.html
> +          </p>
- [ ] Kindly make sure you follow the same design on the mobile version. 

`Your design`

![Capture](https://user-images.githubusercontent.com/64173189/142301747-761d16df-b317-4c80-a3b8-2320ea51b585.JPG)

`original design`

![Capture](https://user-images.githubusercontent.com/64173189/142301815-6d6b792b-cb9c-46f7-8c71-e44124253cb3.JPG)

Resize the images on mobile so that will help you to follow the same design.

2021-11-19 01:45 UTC, ArthurGC approved these changes
# Approved project!  💯 ✅ 🥳 🎈 🎉
Hi  @williamrolando88 

Amazing job implementing suggestions from the previous reviewer! 💯 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media0.giphy.com/media/l0Iyl55kTeh71nTXy/giphy.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-19 01:45 UTC, ArthurGC commented on index.html
>        </p>
- [OPTIONAL] It would be better if you add your own information instead of using the Lorem paragraph(all paragraphs not just the one selected above ). It will help you to have a unique project which you could show in your portfolio as one of your best projects. 😉

2021-11-19 13:55 UTC, merged